### ISSUE TITLE
Rails 4 - Turbolinks - MathJax

### ISSUE THREAD

**Issue by ghost** [reed/turbolinks-compatibility#16]
Hi, I have a Rails4 app which uses MathJax. I use MathJax CDN by placing the following line in the `<head>` section of my app/views/layouts/application.html.erb file:

```
<script type="text/javascript" src="path-to-mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

More information on: http://docs.mathjax.org/en/latest/start.html#mathjax-cdn

Because of Turbolinks, MathJax loads only on the homepage and won't load on other pages unless I refresh the page (which is not desirable). Instead I want MathJax to load only on /Math/New and Physics/Show pages. What should I do?

Thanks a lot for your help.

**Comment by jprinaldi** [comment]
Just a quick update:

In Turbolinks 5, you have to use `turbolinks:load` instead of `page:load`.

**Comment by zengfengbo** [comment]
for caching behavior, cache must be disabled, by adding
  `<meta name="turbolinks-cache-control" content="no-cache">`
