### ISSUE TITLE
fancyBox 2.1.5

### ISSUE THREAD

**Issue by alpracka** [reed/turbolinks-compatibility#30]
Hi,

due to the statement about fancyBox > 2.1.2 here http://reed.github.io/turbolinks-compatibility/fancybox.html im posting this issue.

There are some problems with v2.1.5 and Turbolinks. They were mentioned eariler here in wrong issue https://github.com/rails/turbolinks/issues/96#issuecomment-23225653.  @antpaw also wrote there a partial solution.

So I just want to let you know fancyBox 2.1.5 doesn't work with Turbolinks without modifications and I haven't find 100% solution yet.

**Comment by hwatkins** [comment]
@amree amree Thanks, was having the same issue looks like the bug is the way fancybox is caching the parent, so setting the parent to body fixed it.

**Comment by kelso** [comment]
Thanks @amree! `{ parent: "body" }` fixed it for me.
I've also read the article @alpracka mentioned and it really doesn't work out of the box. Then I found this. Thanks.

**Comment by sheharyarn** [comment]
The solutions above didn't work for me. :(

**Comment by bbnnt** [comment]
yep. as of today, we're stuck

**Comment by sheharyarn** [comment]
I've switched to `magnific-popup`, it has a beautiful and simple API that doesn't conflict with Turbolinks.

**Comment by bbnnt** [comment]
Thanks for the hint, fancybox is old; this have to be said. I actually solved this problem by adding the 'jquery-turbolinks' gem available here on github, a gem that solves some turbolinks binds problems

**Comment by sheharyarn** [comment]
I tried that but it didn't work for me.
