### ISSUE TITLE
Google Adsense strategy not supported by Google Loader

### ISSUE THREAD

**Issue by richardvenneman** [reed/turbolinks-compatibility#36]
Hi there,

Great work on this repo. Thanks to you we've been able to implement fixes for a lot of services.

While integrating Adsense I tried the strategy documented here: http://reed.github.io/turbolinks-compatibility/google_adsense.html. Locally the browser show a white page. It seems to be loading a blocking script from `<script src="http://www.google.com/uds/?file=ads&amp;v=1" type="text/javascript"></script>` initialised by the `google.load 'ads', '1'` call. Is the implementation still working for folks?

The [Google Loader Developer's Guide](https://developers.google.com/loader/#AvailableAPIs) doesn't mention the `ad` service, so it got me wondering if it's still officially supported.

EDIT: The Adsense compatibility code is based on http://www.redkart.com/google_adsense.html. That page states: "Dislaimer: Google cancelled this program, so this no longer works. But, you can check the source of this page to see what used to work." :(

**Comment by pmaojo** [comment]
Hello. I get 
`Exception in queued GPT command TypeError: Cannot read property 'addService' of null
    at Arguments.<anonymous>`

The ad is loaded once but not changing on page load.

**Comment by robypez** [comment]
> Hello. I get
> `Exception in queued GPT command TypeError: Cannot read property 'addService' of null at Arguments.<anonymous>`
> 
> The ad is loaded once but not changing on page load.

Have you solved?

**Comment by pmaojo** [comment]
@robypez I ended up using Google DoubleClick for Publishers to solve this. I won't use Turbolinks again on any project.

starting point: http://reed.github.io/turbolinks-compatibility/doubleclick_for_publishers.html 

I had to learn how to use the platform, so different than AdSense

**Comment by robypez** [comment]
I'm using Google DoubleClick for Publishers, but I still have some issue with turbolinks 5 with this guide

http://reed.github.io/turbolinks-compatibility/doubleclick_for_publishers.html

It doesn't work anymore...

**Comment by pmaojo** [comment]
Sometimes banners are not clickable but, you can see it working here: 
https://motilladelpalancar.net
If I get the time to do it, I will document how I set it up

**Comment by robypez** [comment]
> Sometimes banners are not clickable but, you can see it working here:
> https://motilladelpalancar.net
> If I get the time to do it, I will document how I set it up

Are you using Turbolinks 5?
The issue is with turbolinks 5

**Comment by pmaojo** [comment]
gem 'turbolinks', '~> 5'

**Comment by robypez** [comment]
And without any modification to the code here?

http://reed.github.io/turbolinks-compatibility/doubleclick_for_publishers.html

Because 

```
$(document).on 'page:fetch', => @clearAds()
$(document).on 'page:load', => @evaluate()
```
are not for Turbolinks 5

**Comment by pmaojo** [comment]
With modifications. 

```
class @Gpt
  constructor: ->
    @slots = {}
    window.googletag = googletag || {}
    window.googletag.cmd = googletag.cmd || []

    $(document).on 'turbolinks:before-visit', => @clearAds()
    $(document).on 'turbolinks:load', => @evaluate()

    @evaluate()

  evaluate: ->
    for slot in $('.gpt-ad')
      $slot = $(slot)
      cachedSlot = @slots[$slot.attr('id')]

      if cachedSlot? then @refreshSlot(cachedSlot) else @defineSlot($slot)

  defineSlot: ($slot) ->
    divId = $slot.attr('id')
    path = $slot.data('gpt-path')
    dimensions = $slot.data('gpt-dimensions')

    googletag.cmd.push =>
      slot = googletag.defineSlot(path, dimensions, divId).addService(googletag.pubads())
      googletag.enableServices()
      googletag.display(divId)
      @slots[divId] = slot

  refreshSlot: (slot) ->
    googletag.cmd.push ->
      googletag.pubads().refresh([slot])

  clearAds: ->
    googletag.cmd.push ->
      googletag.pubads().clear()
$ ->
  @gpt ||= new Gpt()

```
