### ISSUE TITLE
jQuery Mobile with Stripe Checkout and Rails

### ISSUE THREAD

**Issue by sealocal** [reed/turbolinks-compatibility#47]
I'd like to see a solution loading Stripe Checkout into a single jQuery Mobile "page".

I am using Rails and jQuery Mobile for my app.  I would like to be able to load Checkout.js only on the payment page.

If I load Checkout with the `script` tag on a jQM page

    <script src="https://checkout.stripe.com/checkout.js"></script>

then I get `Uncaught ReferenceError: StripeCheckout is not defined` in my browser console.

The only way I have solved this problem is by including the `<script>` in the `<head>` of my `layouts/application.html.erb`.  However, since my users will only use the payment form once as a customer, I do not want to load in other pages of my app.

Please share your approach if you've used jQM, Stripe Checkout, and Turbolinks successfully!

**Comment by svisamsetty** [comment]
have you included the configure to happen only after dom is loaded?

**Comment by sealocal** [comment]
@svisamsetty I think my problem is that I don't know how to do that properly with the mixture of Rails / jQuery.  I don't understand what I'm missing.

I've tried wrapping my Stripe `configure` with the line below (where `#new_payment` is the page id), but it doesn't solve the problem.  I don't know how to load the `checkout.js` with that jQM page (which is a Rails view).  I'm not really sure how to express the problem in more detail.

`$( '#new_paymet' ).on( 'pagecreate', function( event, ui ) { }`

Further, I'm not even sure if that event handler should be defined on the *requesting* page or the *requested* page.

**Comment by sealocal** [comment]
I think the question is actually:

**How do I load _any_ remote/external JavaScript file when loading a new jQM page into the DOM?**

I don't know if this is common knowledge or easily found elsewhere, but I just haven't been able to figure it out - especially with knowing that it's possible that Turbolinks could be my problem as well.
