### ISSUE TITLE
Google Tag Manager

### ISSUE THREAD

**Issue by allaire** [reed/turbolinks-compatibility#60]
Anybody had success with GTM and turbolinks? Should I use the same technique as Google UA?

**Comment by infamouse** [comment]
I added a "virtual page view" through the dataLayer which is triggered on "page:change" and caught in GTM with a macro.  Similar to this: http://www.lunametrics.com/blog/2014/09/10/fire-virtual-pageview-google-tag-manager/

**Comment by allaire** [comment]
Yeah did this as well, thanks

**Comment by tboyko** [comment]
For those interested, here's an article on how to do this in the latest revision of GTM. Tested against Rails 4.2.

http://labs.wrprojects.com/how-to-use-google-tag-manager-with-rails-and-turbolinks/

**Comment by nahankid** [comment]
I followed this [http://labs.wrprojects.com/how-to-use-google-tag-manager-with-rails-and-turbolinks/](http://labs.wrprojects.com/how-to-use-google-tag-manager-with-rails-and-turbolinks/). It fires the event twice, the first time. On subsequent navigations, it works fine. Any idea?

**Comment by tboyko** [comment]
Hmm, I'm not seeing that. Make sure that your tag is *only *set to fire on
the custom trigger. It could be that there's a trigger that's firing when
the script is loading also.

There's also the chance that we're seeing differences between versions of
turbolinks, though I wouldn't expect that to matter.
