### ISSUE TITLE
pnotify

### ISSUE THREAD

**Issue by ginter** [reed/turbolinks-compatibility#8]
pnotify doesn't work after loading a page through turbolinks. Looking for a solution now, but thought I'd post this as well.

**Comment by leifcr** [comment]
Newer versions of PNotify needs this initializer, as it for some reason loses it's context/where to place the notifications.
```javascript
$(document).on('turbolinks:load', function() {
  PNotify.prototype.options.stack  = {
    dir1: "down",
    dir2: "left",
    push: "bottom",
    spacing1: 25,
    spacing2: 25,
    context: $("body")
  }     
});
```

Note that if you have a different/custom placement stack, this needs to be changed.
